/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-10-28 05:06:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.tiles.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- Sidebar -->\n");
      out.write("<ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\" id=\"accordionSidebar\" style=\"width: 0 !important; overflow:hidden\">\n");
      out.write("\n");
      out.write("  <!-- Sidebar - Brand -->\n");
      out.write("  <a class=\"sidebar-brand d-flex align-items-center justify-content-center\" href=\"index.html\">\n");
      out.write("    <div class=\"sidebar-brand-icon rotate-n-15\">\n");
      out.write("      <i class=\"fas fa-laugh-wink\"></i>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"sidebar-brand-text mx-3\">SB Admin <sup>2</sup></div>\n");
      out.write("  </a>\n");
      out.write("\n");
      out.write("  <!-- Divider -->\n");
      out.write("  <hr class=\"sidebar-divider my-0\">\n");
      out.write("\n");
      out.write("  <!-- Nav Item - Dashboard -->\n");
      out.write("  <li class=\"nav-item active\">\n");
      out.write("    <a class=\"nav-link\" href=\"index.html\">\n");
      out.write("      <i class=\"fas fa-fw fa-tachometer-alt\"></i>\n");
      out.write("      <span>Dashboard</span></a>\n");
      out.write("  </li>\n");
      out.write("\n");
      out.write("  <!-- Divider -->\n");
      out.write("  <hr class=\"sidebar-divider\">\n");
      out.write("\n");
      out.write("  <!-- Heading -->\n");
      out.write("  <div class=\"sidebar-heading\">\n");
      out.write("    Interface\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Nav Item - Pages Collapse Menu -->\n");
      out.write("  <li class=\"nav-item\">\n");
      out.write("    <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseTwo\" aria-expanded=\"true\" aria-controls=\"collapseTwo\">\n");
      out.write("      <i class=\"fas fa-fw fa-cog\"></i>\n");
      out.write("      <span>Components</span>\n");
      out.write("    </a>\n");
      out.write("    <div id=\"collapseTwo\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\n");
      out.write("      <div class=\"bg-white py-2 collapse-inner rounded\">\n");
      out.write("        <h6 class=\"collapse-header\">Custom Components:</h6>\n");
      out.write("        <a class=\"collapse-item\" href=\"buttons.html\">Buttons</a>\n");
      out.write("        <a class=\"collapse-item\" href=\"cards.html\">Cards</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </li>\n");
      out.write("\n");
      out.write("  <!-- Nav Item - Utilities Collapse Menu -->\n");
      out.write("  <li class=\"nav-item\">\n");
      out.write("    <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseUtilities\" aria-expanded=\"true\" aria-controls=\"collapseUtilities\">\n");
      out.write("      <i class=\"fas fa-fw fa-wrench\"></i>\n");
      out.write("      <span>Utilities</span>\n");
      out.write("    </a>\n");
      out.write("    <div id=\"collapseUtilities\" class=\"collapse\" aria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\n");
      out.write("      <div class=\"bg-white py-2 collapse-inner rounded\">\n");
      out.write("        <h6 class=\"collapse-header\">Custom Utilities:</h6>\n");
      out.write("        <a class=\"collapse-item\" href=\"utilities-color.html\">Colors</a>\n");
      out.write("        <a class=\"collapse-item\" href=\"utilities-border.html\">Borders</a>\n");
      out.write("        <a class=\"collapse-item\" href=\"utilities-animation.html\">Animations</a>\n");
      out.write("        <a class=\"collapse-item\" href=\"utilities-other.html\">Other</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </li>\n");
      out.write("\n");
      out.write("  <!-- Divider -->\n");
      out.write("  <hr class=\"sidebar-divider\">\n");
      out.write("\n");
      out.write("  <!-- Heading -->\n");
      out.write("  <div class=\"sidebar-heading\">\n");
      out.write("    Addons\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Nav Item - Pages Collapse Menu -->\n");
      out.write("  <li class=\"nav-item\">\n");
      out.write("    <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapsePages\" aria-expanded=\"true\" aria-controls=\"collapsePages\">\n");
      out.write("      <i class=\"fas fa-fw fa-folder\"></i>\n");
      out.write("      <span>Pages</span>\n");
      out.write("    </a>\n");
      out.write("    <div id=\"collapsePages\" class=\"collapse\" aria-labelledby=\"headingPages\" data-parent=\"#accordionSidebar\">\n");
      out.write("      <div class=\"bg-white py-2 collapse-inner rounded\">\n");
      out.write("        <h6 class=\"collapse-header\">Login Screens:</h6>\n");
      out.write("        <a class=\"collapse-item\" href=\"login.html\">Login</a>\n");
      out.write("        <a class=\"collapse-item\" href=\"register.html\">Register</a>\n");
      out.write("        <a class=\"collapse-item\" href=\"forgot-password.html\">Forgot Password</a>\n");
      out.write("        <div class=\"collapse-divider\"></div>\n");
      out.write("        <h6 class=\"collapse-header\">Other Pages:</h6>\n");
      out.write("        <a class=\"collapse-item\" href=\"404.html\">404 Page</a>\n");
      out.write("        <a class=\"collapse-item\" href=\"blank.html\">Blank Page</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </li>\n");
      out.write("\n");
      out.write("  <!-- Nav Item - Charts -->\n");
      out.write("  <li class=\"nav-item\">\n");
      out.write("    <a class=\"nav-link\" href=\"charts.html\">\n");
      out.write("      <i class=\"fas fa-fw fa-chart-area\"></i>\n");
      out.write("      <span>Charts</span></a>\n");
      out.write("  </li>\n");
      out.write("\n");
      out.write("  <!-- Nav Item - Tables -->\n");
      out.write("  <li class=\"nav-item\">\n");
      out.write("    <a class=\"nav-link\" href=\"tables.html\">\n");
      out.write("      <i class=\"fas fa-fw fa-table\"></i>\n");
      out.write("      <span>Tables</span></a>\n");
      out.write("  </li>\n");
      out.write("\n");
      out.write("  <!-- Divider -->\n");
      out.write("  <hr class=\"sidebar-divider d-none d-md-block\">\n");
      out.write("\n");
      out.write("  <!-- Sidebar Toggler (Sidebar) -->\n");
      out.write("  <div class=\"text-center d-none d-md-inline\">\n");
      out.write("    <button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</ul>\n");
      out.write("<!-- End of Sidebar -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
